apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: app1
    spec:
      containers:
        - image: dwinurhadi17/app1
          name: app1
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
